# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      PYTHON_VERSION: '3.10'
      addToPath: true
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- script: python -m venv venv
  displayName: 'Create Python virtual environment'

- script: |
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python manage.py check
  displayName: 'Run Django checks'

- script: |
    source venv/bin/activate
    python manage.py test
  displayName: 'Run Django tests'

- script: |
    echo "No database configuration needed"
  displayName: 'Skip database setup'


- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(72691d6b-a80a-4854-8670-a03cd024f434)'
    appType: 'webAppLinux'
    appName: 'Rohit-WeatherApp'
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
  displayName: 'Deploy to Azure Web App'
